### ISSUE TITLE
Not working on ubuntu

### ISSUE THREAD

**Issue by Joncy** [netbeast-co/xy-package-manager#1]
salas@ubuntu:~/web$ xway new
/usr/bin/env: node: No existe el archivo o el directorio

node.js in ubuntu is called nodejs because of a packet conflict name, also, installing from apt-get sets node's executable to be in /usr/bin and not /usr/bin/env

**Comment by Joncy** [comment]
Issue can be fixed editing the shebang at line 1:
#!/usr/bin/env node
to
#!/usr/bin/nodejs

**Comment by jesusdario** [comment]
I tried instead using a "2 step" shebang: 
```bash
#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"
```

The script now always starts as `sh` but changes to node or nodejs depending on the version found.

src: http://unix.stackexchange.com/questions/65235/universal-node-js-shebang

**Comment by Joncy** [comment]
Tested, that does the job!
